quarkus.hibernate-reactive.active=false
quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=devser
quarkus.datasource.password=admin123
quarkus.datasource.jdbc.url=jdbc:postgresql://192.168.178.41:5432/animevote
quarkus.hibernate-orm.database.generation=drop-and-create
