quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=devser
quarkus.datasource.password=admin123
quarkus.datasource.jdbc.url=jdbc:postgresql://192.168.178.41:31432/animevote
quarkus.datasource.reactive.url=vertx-reactive:postgresql://192.168.178.41:31432/animevote
quarkus.datasource.reactive.max-size=5
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
